In [1]:
# load artifacts (from disk)
import json, pandas as pd
from chessrl.eval.helpers import (
    vi_move_from_policy_map, vi_move_from_values,
    mcts_move_from_instance,
)
from chessrl.eval.evaluator import evaluate
from chessrl.algorithms.mcts import MCTS
from chessrl.eval.helpers import optimal_moves_syzygy

# load artifacts (from disk)
from chessrl.utils.io import load_vf_parquet, load_policy_jsonl

2025-08-30 10:36:19,969 - INFO - Loading config file...

In [2]:
TB_PATH = "../../../tablebase/krk/"

# dtm oracle
dtz_oracle = pd.read_csv(TB_PATH + "krk_full.csv").set_index("fen")["dtz"].to_dict()
dtm_oracle = lambda fen: abs(int(dtz_oracle[fen]))

# optimal moves source
opt_moves   = optimal_moves_syzygy(TB_PATH)

# evaluate (same function for all)
test_fens = [ "8/8/8/8/8/8/k7/2K4R w - - 0 1", "8/8/8/8/8/8/k7/2K2R2 w - - 0 1", "8/8/8/8/8/8/k7/2K4R w - - 0 1" ]

# MCTS

In [3]:
# 3) MCTS
mcts = MCTS(iterations=10000, seconds=0.0)
move_fn = mcts_move_from_instance(mcts, "seconds")
df_mcts   = evaluate(move_fn, test_fens, TB_PATH, dtm_oracle, optimal_moves=opt_moves, budget=6.0) # budget is in seconds
df_mcts

KeyboardInterrupt:

# Value Iteration

## from policy

In [14]:
from chessrl.env import SyzygyDefender
defender = SyzygyDefender(TB_PATH)

In [15]:
# choose version to test
policy_map = load_policy_jsonl("../../../artifacts/policies/vi_krk_greedy_intermediate_13.jsonl")

#simple mate in one endgame
test_fens = ["k7/2R5/1K6/8/8/8/8/8 w - - 0 1",
             "6k1/8/6K1/8/8/8/1R6/8 w - - 0 1",
            "6k1/8/8/6K1/8/8/1R6/8 w - - 0 1",
            "8/1k6/3R4/8/8/4K3/8/8 w - - 0 1",
            "8/8/8/8/8/8/4k3/3R2K1 w - - 0 1",
            "7k/8/8/8/8/4R3/4K3/8 w - - 0 1",
            "4k3/8/8/8/8/8/1R6/4K3 w - - 0 1",
	        "8/8/8/4k3/8/3K4/8/1R6 w - - 0 1"]

# Load the test data
test_df = pd.read_csv(TB_PATH + "krk_test.csv")

# Calculate DTM (absolute value of DTZ)
test_df['dtm'] = test_df['dtz'].abs()

# Sample 2 positions for each unique DTM value
test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]

vi_agent = vi_move_from_policy_map(policy_map)
df_vi     = evaluate(vi_agent, defender, test_fens, dtm_oracle, optimal_moves=opt_moves)
df_vi

/var/folders/36/dqn14xy95j93q4nqhpjrg0s80000gn/T/ipykernel_7624/2879828245.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,8/8/k1K5/8/8/8/8/7R w - - 0 1,1,1,0.0,1,0.007375,1.000000,1,None
1,5k2/8/5K2/8/8/8/7R/8 w - - 0 1,1,1,0.0,1,0.001125,1.000000,1,None
2,4R3/8/8/8/8/7K/8/6k1 w - - 0 1,3,3,0.0,1,0.002084,1.000000,2,None
3,8/8/8/3R4/5K2/8/8/4k3 w - - 0 1,3,3,0.0,1,0.002042,1.000000,2,None
4,k2K4/8/5R2/8/8/8/8/8 w - - 0 1,5,5,0.0,1,0.002097,1.000000,3,None
5,8/8/8/6R1/8/k7/3K4/8 w - - 0 1,5,5,0.0,1,0.001070,1.000000,3,None
6,8/8/8/8/8/4K3/4R3/k7 w - - 0 1,7,7,0.0,1,0.001167,1.000000,4,None
7,R3K1k1/8/8/8/8/8/8/8 w - - 0 1,7,7,0.0,1,0.001677,1.000000,4,None
8,8/3R4/8/8/8/4K3/8/1k6 w - - 0 1,9,9,0.0,1,0.001175,1.000000,5,None
9,8/8/6K1/6R1/8/8/7k/8 w - - 0 1,9,9,0.0,1,0.001525,1.000000,5,None
10,3k1K2/8/8/7R/8/8/8/8 w - - 0 1,11,11,0.0,1,0.004548,1.000000,6,None
11,8/8/7k/8/5K2/8/3R4/8 w - - 0 1,11,11,0.0,1,0.003146,1.000000,6,None
12,8/8/7K/4R3/8/7k/8/8 w - - 0 1,13,13,0.0,1,0.002036,1.000000,7,None
13,6R1/8/7k/8/8/7K/8/8 w - - 0 1,13,13,0.0,1,0.001988,1.000000,7,None
14,8/8/5R2/8/4K3/8/4k3/8 w - - 0 1,15,15,0.0,1,0.001713,1.000000,8,None
15,8/8/1k6/8/2K5/8/6R1/8 w - - 0 1,15,15,0.0,1,0.001495,1.000000,8,None
16,5K2/5R2/7k/8/8/8/8/8 w - - 0 1,17,17,0.0,1,0.001583,1.000000,9,None
17,8/8/8/1K6/8/6R1/7k/8 w - - 0 1,17,17,0.0,1,0.001176,1.000000,9,None
18,8/3R1K2/8/8/8/8/8/6k1 w - - 0 1,19,19,0.0,1,0.001633,1.000000,10,None
19,8/7k/8/8/8/1K6/3R4/8 w - - 0 1,19,19,0.0,1,0.001117,1.000000,10,None
20,8/2k5/8/8/8/5R2/1K6/8 w - - 0 1,21,21,0.0,1,0.001220,1.000000,11,None
21,8/8/8/1K6/7k/8/3R4/8 w - - 0 1,21,21,0.0,1,0.001398,1.000000,11,None
22,K7/R7/8/8/8/8/7k/8 w - - 0 1,23,23,0.0,1,0.001528,1.000000,12,None
23,8/1k6/8/R7/7K/8/8/8 w - - 0 1,23,23,0.0,1,0.001306,1.000000,12,None
24,8/8/2k5/7K/7R/8/8/8 w - - 0 1,25,25,0.0,1,0.001192,1.000000,13,None
25,8/1R6/4k3/8/8/1K6/8/8 w - - 0 1,25,25,0.0,1,0.001224,1.000000,13,None
26,4K3/8/8/8/8/3k4/8/7R w - - 0 1,300,27,NaN,0,0.000456,0.493333,150,None
27,K7/8/8/8/8/8/2k5/5R2 w - - 0 1,300,27,NaN,0,0.000336,0.493333,150,None
28,KR6/8/8/8/4k3/8/8/8 w - - 0 1,300,29,NaN,0,0.000423,0.486667,150,None
29,2R5/3k4/8/8/8/8/1K6/8 w - - 0 1,300,29,NaN,0,0.000319,0.006667,150,None
30,8/7K/8/8/8/2k5/1R6/8 w - - 0 1,300,31,NaN,0,0.000390,0.006667,150,None
31,6R1/8/5k2/8/8/8/8/K7 w - - 0 1,300,31,NaN,0,0.000271,0.506667,150,None

## from value function

In [ ]:
V = load_vf_parquet("../../../artifacts/values/vi_krk_values.parquet")

vi_v_agent = vi_move_from_values(V, TB_PATH)

df_vi_v   = evaluate(vi_v_agent, test_fens, TB_PATH, dtm_oracle, optimal_moves=opt_moves)
df_vi_v

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,8/8/k1K5/8/8/8/8/7R w - - 0 1,1,1,0,1,25.856577,1.0,1,None
1,5k2/8/5K2/8/8/8/7R/8 w - - 0 1,1,1,0,1,25.288614,1.0,1,None
2,4R3/8/8/8/8/7K/8/6k1 w - - 0 1,3,3,0,1,21.080375,1.0,2,None
3,8/8/8/3R4/5K2/8/8/4k3 w - - 0 1,3,3,0,1,30.670188,1.0,2,None
4,k2K4/8/5R2/8/8/8/8/8 w - - 0 1,5,5,0,1,18.113335,1.0,3,None
5,8/8/8/6R1/8/k7/3K4/8 w - - 0 1,5,5,0,1,28.339297,1.0,3,None
6,8/8/8/8/8/4K3/4R3/k7 w - - 0 1,7,7,0,1,21.968189,1.0,4,None
7,R3K1k1/8/8/8/8/8/8/8 w - - 0 1,7,7,0,1,18.504751,1.0,4,None
8,8/3R4/8/8/8/4K3/8/1k6 w - - 0 1,9,9,0,1,27.736651,1.0,5,None
9,8/8/6K1/6R1/8/8/7k/8 w - - 0 1,9,9,0,1,25.457139,1.0,5,None
10,3k1K2/8/8/7R/8/8/8/8 w - - 0 1,11,11,0,1,23.623822,1.0,6,None
11,8/8/7k/8/5K2/8/3R4/8 w - - 0 1,11,11,0,1,29.867056,1.0,6,None
12,8/8/7K/4R3/8/7k/8/8 w - - 0 1,13,13,0,1,23.232415,1.0,7,None
13,6R1/8/7k/8/8/7K/8/8 w - - 0 1,13,13,0,1,50.811510,1.0,7,None
14,8/8/5R2/8/4K3/8/4k3/8 w - - 0 1,15,15,0,1,25.364539,1.0,8,None
15,8/8/1k6/8/2K5/8/6R1/8 w - - 0 1,15,15,0,1,31.108868,1.0,8,None
16,5K2/5R2/7k/8/8/8/8/8 w - - 0 1,17,17,0,1,22.413620,1.0,9,None
17,8/8/8/1K6/8/6R1/7k/8 w - - 0 1,17,17,0,1,33.784516,1.0,9,None
18,8/3R1K2/8/8/8/8/8/6k1 w - - 0 1,19,19,0,1,31.382272,1.0,10,None
19,8/7k/8/8/8/1K6/3R4/8 w - - 0 1,19,19,0,1,26.094457,1.0,10,None
20,8/2k5/8/8/8/5R2/1K6/8 w - - 0 1,21,21,0,1,34.226336,1.0,11,None
21,8/8/8/1K6/7k/8/3R4/8 w - - 0 1,21,21,0,1,27.280199,1.0,11,None
22,K7/R7/8/8/8/8/7k/8 w - - 0 1,23,23,0,1,47.177514,1.0,12,None
23,8/1k6/8/R7/7K/8/8/8 w - - 0 1,23,23,0,1,31.878371,1.0,12,None
24,8/8/2k5/7K/7R/8/8/8 w - - 0 1,25,25,0,1,27.014726,1.0,13,None
25,8/1R6/4k3/8/8/1K6/8/8 w - - 0 1,25,25,0,1,35.571341,1.0,13,None
26,4K3/8/8/8/8/3k4/8/7R w - - 0 1,27,27,0,1,32.854017,1.0,14,None
27,K7/8/8/8/8/8/2k5/5R2 w - - 0 1,27,27,0,1,33.798091,1.0,14,None
28,KR6/8/8/8/4k3/8/8/8 w - - 0 1,29,29,0,1,33.356773,1.0,15,None
29,2R5/3k4/8/8/8/8/1K6/8 w - - 0 1,29,29,0,1,35.262157,1.0,15,None
30,8/7K/8/8/8/2k5/1R6/8 w - - 0 1,31,31,0,1,30.918362,1.0,16,None
31,6R1/8/5k2/8/8/8/8/K7 w - - 0 1,31,31,0,1,52.219180,1.0,16,None

## value function vs random defender

In [3]:
from chessrl import RandomDefender, SyzygyDefender


# Load the test data
test_df = pd.read_csv(TB_PATH + "krk_test.csv")

# Calculate DTM (absolute value of DTZ)
test_df['dtm'] = test_df['dtz'].abs()

test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]

/tmp/ipykernel_9021/201573114.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]

In [ ]:

V = load_vf_parquet("../../../artifacts/values/vi_krk_values.parquet")

vi_v_agent = vi_move_from_values(V, TB_PATH)

df_vi_v   = evaluate(vi_v_agent, RandomDefender(3), test_fens, dtm_oracle, optimal_moves=opt_moves)
df_vi_v

# TD methods

### Q-learning

In [16]:
# choose version to test
policy_map = load_policy_jsonl("../../../artifacts/policies/vi_krk_greedy_intermediate_13.jsonl")

#simple mate in one endgame
test_fens = ["k7/2R5/1K6/8/8/8/8/8 w - - 0 1",
             "6k1/8/6K1/8/8/8/1R6/8 w - - 0 1",
            "6k1/8/8/6K1/8/8/1R6/8 w - - 0 1",
            "8/1k6/3R4/8/8/4K3/8/8 w - - 0 1",
            "8/8/8/8/8/8/4k3/3R2K1 w - - 0 1",
            "7k/8/8/8/8/4R3/4K3/8 w - - 0 1",
            "4k3/8/8/8/8/8/1R6/4K3 w - - 0 1",
	        "8/8/8/4k3/8/3K4/8/1R6 w - - 0 1"]

# Load the test data
test_df = pd.read_csv(TB_PATH + "krk_test.csv")

# Calculate DTM (absolute value of DTZ)
test_df['dtm'] = test_df['dtz'].abs()

# Sample 2 positions for each unique DTM value
test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"].tolist()

/var/folders/36/dqn14xy95j93q4nqhpjrg0s80000gn/T/ipykernel_7624/3205953368.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"].tolist()

In [17]:
# Load Q-Learning policy
qlearning_policy = load_policy_jsonl("../../../artifacts/policies/TD_QLearning_krk_greedy.jsonl")
qlearning_agent = vi_move_from_policy_map(qlearning_policy)

### Sarsa

In [5]:
sarsa_policy = load_policy_jsonl("../../../artifacts/policies/TD_SARSA_krk_greedy.jsonl")
sarsa_agent = vi_move_from_policy_map(sarsa_policy)

In [6]:
df_sarsa = evaluate(sarsa_agent, SyzygyDefender(TB_PATH), test_fens, dtm_oracle, optimal_moves=opt_moves)

In [7]:
df_sarsa

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,8/8/k1K5/8/8/8/8/7R w - - 0 1,1,1,0.0,1,0.005363,1.000000,1,None
1,5k2/8/5K2/8/8/8/7R/8 w - - 0 1,300,1,NaN,0,0.002528,0.266667,150,None
2,4R3/8/8/8/8/7K/8/6k1 w - - 0 1,300,3,NaN,0,0.002779,0.340000,150,None
3,8/8/8/3R4/5K2/8/8/4k3 w - - 0 1,6,3,NaN,0,0.002784,0.000000,3,None
4,k2K4/8/5R2/8/8/8/8/8 w - - 0 1,300,5,NaN,0,0.003121,0.033333,150,None
5,8/8/8/6R1/8/k7/3K4/8 w - - 0 1,4,5,NaN,0,0.012897,0.000000,2,None
6,8/8/8/8/8/4K3/4R3/k7 w - - 0 1,300,7,NaN,0,0.002512,0.166667,150,None
7,R3K1k1/8/8/8/8/8/8/8 w - - 0 1,6,7,NaN,0,0.002450,0.000000,3,None
8,8/3R4/8/8/8/4K3/8/1k6 w - - 0 1,300,9,NaN,0,0.002612,0.493333,150,None
9,8/8/6K1/6R1/8/8/7k/8 w - - 0 1,2,9,NaN,0,0.002581,0.000000,1,None
10,3k1K2/8/8/7R/8/8/8/8 w - - 0 1,300,11,NaN,0,0.003092,0.640000,150,None
11,8/8/7k/8/5K2/8/3R4/8 w - - 0 1,300,11,NaN,0,0.002746,0.026667,150,None
12,8/8/7K/4R3/8/7k/8/8 w - - 0 1,300,13,NaN,0,0.002596,0.326667,150,None
13,6R1/8/7k/8/8/7K/8/8 w - - 0 1,300,13,NaN,0,0.002599,0.133333,150,None
14,8/8/5R2/8/4K3/8/4k3/8 w - - 0 1,300,15,NaN,0,0.002444,0.493333,150,None
15,8/8/1k6/8/2K5/8/6R1/8 w - - 0 1,300,15,NaN,0,0.003003,0.653333,150,None
16,5K2/5R2/7k/8/8/8/8/8 w - - 0 1,300,17,NaN,0,0.003508,0.660000,150,None
17,8/8/8/1K6/8/6R1/7k/8 w - - 0 1,2,17,NaN,0,0.003183,0.000000,1,None
18,8/3R1K2/8/8/8/8/8/6k1 w - - 0 1,300,19,NaN,0,0.003223,0.033333,150,None
19,8/7k/8/8/8/1K6/3R4/8 w - - 0 1,300,19,NaN,0,0.002795,0.493333,150,None
20,8/2k5/8/8/8/5R2/1K6/8 w - - 0 1,300,21,NaN,0,0.002908,0.353333,150,None
21,8/8/8/1K6/7k/8/3R4/8 w - - 0 1,300,21,NaN,0,0.003111,0.266667,150,None
22,K7/R7/8/8/8/8/7k/8 w - - 0 1,300,23,NaN,0,0.002823,0.493333,150,None
23,8/1k6/8/R7/7K/8/8/8 w - - 0 1,300,23,NaN,0,0.002946,0.486667,150,None
24,8/8/2k5/7K/7R/8/8/8 w - - 0 1,300,25,NaN,0,0.002754,0.320000,150,None
25,8/1R6/4k3/8/8/1K6/8/8 w - - 0 1,300,25,NaN,0,0.002855,0.426667,150,None
26,4K3/8/8/8/8/3k4/8/7R w - - 0 1,300,27,NaN,0,0.002651,0.033333,150,None
27,K7/8/8/8/8/8/2k5/5R2 w - - 0 1,300,27,NaN,0,0.002347,0.013333,150,None
28,KR6/8/8/8/4k3/8/8/8 w - - 0 1,300,29,NaN,0,0.002898,0.046667,150,None
29,2R5/3k4/8/8/8/8/1K6/8 w - - 0 1,300,29,NaN,0,0.002344,0.046667,150,None
30,8/7K/8/8/8/2k5/1R6/8 w - - 0 1,300,31,NaN,0,0.002683,0.186667,150,None
31,6R1/8/5k2/8/8/8/8/K7 w - - 0 1,300,31,NaN,0,0.002373,0.020000,150,None

In [8]:
df_sarsa_random = evaluate(sarsa_agent, RandomDefender(0), test_fens, dtm_oracle, optimal_moves=opt_moves)
df_sarsa_random

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,8/8/k1K5/8/8/8/8/7R w - - 0 1,1,1,0.0,1,0.002121,1.000000,1,None
1,5k2/8/5K2/8/8/8/7R/8 w - - 0 1,114,1,NaN,0,0.002735,0.087719,57,None
2,4R3/8/8/8/8/7K/8/6k1 w - - 0 1,30,3,NaN,0,0.002639,0.200000,15,None
3,8/8/8/3R4/5K2/8/8/4k3 w - - 0 1,174,3,NaN,0,0.002944,0.091954,87,None
4,k2K4/8/5R2/8/8/8/8/8 w - - 0 1,150,5,NaN,0,0.002736,0.040000,75,None
5,8/8/8/6R1/8/k7/3K4/8 w - - 0 1,124,5,NaN,0,0.002907,0.096774,62,None
6,8/8/8/8/8/4K3/4R3/k7 w - - 0 1,20,7,NaN,0,0.002752,0.100000,10,None
7,R3K1k1/8/8/8/8/8/8/8 w - - 0 1,64,7,NaN,0,0.002498,0.093750,32,None
8,8/3R4/8/8/8/4K3/8/1k6 w - - 0 1,300,9,NaN,0,0.003952,0.140000,150,None
9,8/8/6K1/6R1/8/8/7k/8 w - - 0 1,28,9,NaN,0,0.002314,0.357143,14,None
10,3k1K2/8/8/7R/8/8/8/8 w - - 0 1,28,11,NaN,0,0.002290,0.214286,14,None
11,8/8/7k/8/5K2/8/3R4/8 w - - 0 1,300,11,NaN,0,0.002467,0.073333,150,None
12,8/8/7K/4R3/8/7k/8/8 w - - 0 1,138,13,NaN,0,0.002338,0.101449,69,None
13,6R1/8/7k/8/8/7K/8/8 w - - 0 1,8,13,NaN,0,0.002527,0.000000,4,None
14,8/8/5R2/8/4K3/8/4k3/8 w - - 0 1,16,15,NaN,0,0.002431,0.125000,8,None
15,8/8/1k6/8/2K5/8/6R1/8 w - - 0 1,272,15,NaN,0,0.002427,0.117647,136,None
16,5K2/5R2/7k/8/8/8/8/8 w - - 0 1,70,17,NaN,0,0.002635,0.171429,35,None
17,8/8/8/1K6/8/6R1/7k/8 w - - 0 1,6,17,NaN,0,0.002207,0.000000,3,None
18,8/3R1K2/8/8/8/8/8/6k1 w - - 0 1,162,19,NaN,0,0.002733,0.209877,81,None
19,8/7k/8/8/8/1K6/3R4/8 w - - 0 1,176,19,NaN,0,0.002586,0.045455,88,None
20,8/2k5/8/8/8/5R2/1K6/8 w - - 0 1,300,21,NaN,0,0.002913,0.153333,150,None
21,8/8/8/1K6/7k/8/3R4/8 w - - 0 1,300,21,NaN,0,0.003105,0.106667,150,None
22,K7/R7/8/8/8/8/7k/8 w - - 0 1,28,23,NaN,0,0.002911,0.214286,14,None
23,8/1k6/8/R7/7K/8/8/8 w - - 0 1,242,23,NaN,0,0.003205,0.157025,121,None
24,8/8/2k5/7K/7R/8/8/8 w - - 0 1,70,25,NaN,0,0.003394,0.142857,35,None
25,8/1R6/4k3/8/8/1K6/8/8 w - - 0 1,160,25,NaN,0,0.003171,0.125000,80,None
26,4K3/8/8/8/8/3k4/8/7R w - - 0 1,136,27,NaN,0,0.003130,0.117647,68,None
27,K7/8/8/8/8/8/2k5/5R2 w - - 0 1,6,27,NaN,0,0.002710,0.000000,3,None
28,KR6/8/8/8/4k3/8/8/8 w - - 0 1,116,29,NaN,0,0.003103,0.120690,58,None
29,2R5/3k4/8/8/8/8/1K6/8 w - - 0 1,26,29,NaN,0,0.002886,0.307692,13,None
30,8/7K/8/8/8/2k5/1R6/8 w - - 0 1,174,31,NaN,0,0.002933,0.126437,87,None
31,6R1/8/5k2/8/8/8/8/K7 w - - 0 1,300,31,NaN,0,0.002935,0.066667,150,None

# Actor-Critic

In [13]:
from chessrl.algorithms.actor_critic.ac_batch import ActorCritic
from chessrl.eval.helpers import vi_move_from_policy_nn
from chessrl.env import SyzygyDefender
TB_PATH = "../../../tablebase/krk/"
defender = SyzygyDefender(TB_PATH)
from chessrl.eval.helpers import optimal_moves_syzygy

import pandas as pd
from chessrl.eval.evaluator import evaluate

# dtm oracle
dtz_oracle = pd.read_csv(TB_PATH + "krk_full.csv").set_index("fen")["dtz"].to_dict()
dtm_oracle = lambda fen: abs(int(dtz_oracle[fen]))

# optimal moves source
opt_moves = optimal_moves_syzygy(TB_PATH)

#simple mate in one endgame
test_fens = ["k7/2R5/1K6/8/8/8/8/8 w - - 0 1",
             "6k1/8/6K1/8/8/8/1R6/8 w - - 0 1",
            "6k1/8/8/6K1/8/8/1R6/8 w - - 0 1",
            "8/1k6/3R4/8/8/4K3/8/8 w - - 0 1",
            "8/8/8/8/8/8/4k3/3R2K1 w - - 0 1",
            "7k/8/8/8/8/4R3/4K3/8 w - - 0 1",
            "4k3/8/8/8/8/8/1R6/4K3 w - - 0 1",
	        "8/8/8/4k3/8/3K4/8/1R6 w - - 0 1"]

# Load the test data
test_df = pd.read_csv(TB_PATH + "krk_test.csv")

# Calculate DTM (absolute value of DTZ)
test_df['dtm'] = test_df['dtz'].abs()

# Sample 2 positions for each unique DTM value
test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]

agent = ActorCritic(tb_path=TB_PATH)

agent.load_checkpoint("../algorithms/actor_critic/output/checkpoint_ac_original_final.pth")

move_fn = vi_move_from_policy_nn(agent.policy)
df_ac = evaluate(move_fn, defender, test_fens, dtm_oracle, optimal_moves=opt_moves)
df_ac

/var/folders/36/dqn14xy95j93q4nqhpjrg0s80000gn/T/ipykernel_22851/1124171412.py:35: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_fens = test_df.groupby('dtm').apply(lambda x: x.sample(min(2, len(x)), random_state=42)).reset_index(drop=True)["fen"]
2025-08-30 23:06:43,621 - INFO - Using MPS device for acceleration
2025-08-30 23:06:43,861 - INFO - Loaded checkpoint from ../algorithms/actor_critic/output/checkpoint_ac_original_final.pth

,fen,dtm_policy,dtm_oracle,gap,success,ms_per_move,top1,top1_decisions,budget
0,8/8/k1K5/8/8/8/8/7R w - - 0 1,6,1,None,0,4.799945,0.000000,3,None
1,5k2/8/5K2/8/8/8/7R/8 w - - 0 1,300,1,None,0,4.115287,0.000000,150,None
2,4R3/8/8/8/8/7K/8/6k1 w - - 0 1,300,3,None,0,4.217480,0.480000,150,None
3,8/8/8/3R4/5K2/8/8/4k3 w - - 0 1,10,3,None,0,4.153350,0.000000,5,None
4,k2K4/8/5R2/8/8/8/8/8 w - - 0 1,300,5,None,0,4.162055,0.240000,150,None
5,8/8/8/6R1/8/k7/3K4/8 w - - 0 1,300,5,None,0,4.247871,0.460000,150,None
6,8/8/8/8/8/4K3/4R3/k7 w - - 0 1,2,7,None,0,4.362750,0.000000,1,None
7,R3K1k1/8/8/8/8/8/8/8 w - - 0 1,300,7,None,0,4.209036,0.320000,150,None
8,8/3R4/8/8/8/4K3/8/1k6 w - - 0 1,300,9,None,0,4.342112,0.493333,150,None
9,8/8/6K1/6R1/8/8/7k/8 w - - 0 1,2,9,None,0,4.104417,0.000000,1,None
10,3k1K2/8/8/7R/8/8/8/8 w - - 0 1,300,11,None,0,4.196862,0.493333,150,None
11,8/8/7k/8/5K2/8/3R4/8 w - - 0 1,300,11,None,0,4.154409,0.360000,150,None
12,8/8/7K/4R3/8/7k/8/8 w - - 0 1,300,13,None,0,4.180946,0.386667,150,None
13,6R1/8/7k/8/8/7K/8/8 w - - 0 1,300,13,None,0,3.993388,0.493333,150,None
14,8/8/5R2/8/4K3/8/4k3/8 w - - 0 1,300,15,None,0,4.224442,0.466667,150,None
15,8/8/1k6/8/2K5/8/6R1/8 w - - 0 1,300,15,None,0,4.219575,0.006667,150,None
16,5K2/5R2/7k/8/8/8/8/8 w - - 0 1,300,17,None,0,4.231374,0.486667,150,None
17,8/8/8/1K6/8/6R1/7k/8 w - - 0 1,300,17,None,0,4.242165,0.486667,150,None
18,8/3R1K2/8/8/8/8/8/6k1 w - - 0 1,6,19,None,0,4.205930,0.000000,3,None
19,8/7k/8/8/8/1K6/3R4/8 w - - 0 1,300,19,None,0,4.250360,0.253333,150,None
20,8/2k5/8/8/8/5R2/1K6/8 w - - 0 1,300,21,None,0,4.216834,0.000000,150,None
21,8/8/8/1K6/7k/8/3R4/8 w - - 0 1,300,21,None,0,4.224803,0.000000,150,None
22,K7/R7/8/8/8/8/7k/8 w - - 0 1,300,23,None,0,4.179966,0.493333,150,None
23,8/1k6/8/R7/7K/8/8/8 w - - 0 1,2,23,None,0,4.256208,0.000000,1,None
24,8/8/2k5/7K/7R/8/8/8 w - - 0 1,300,25,None,0,4.181431,0.000000,150,None
25,8/1R6/4k3/8/8/1K6/8/8 w - - 0 1,6,25,None,0,4.131639,0.000000,3,None
26,4K3/8/8/8/8/3k4/8/7R w - - 0 1,300,27,None,0,4.204848,0.326667,150,None
27,K7/8/8/8/8/8/2k5/5R2 w - - 0 1,300,27,None,0,4.221891,0.493333,150,None
28,KR6/8/8/8/4k3/8/8/8 w - - 0 1,300,29,None,0,4.191006,0.493333,150,None
29,2R5/3k4/8/8/8/8/1K6/8 w - - 0 1,300,29,None,0,4.254103,0.326667,150,None
30,8/7K/8/8/8/2k5/1R6/8 w - - 0 1,300,31,None,0,4.207691,0.386667,150,None
31,6R1/8/5k2/8/8/8/8/K7 w - - 0 1,300,31,None,0,4.161450,0.006667,150,None